import type { StoreData } from "./types";

export const seedData: StoreData = {
  store: {
    name: "Custom Eco",
    contact_email: "hello@customeco.com",
    subdomain: "custom-eco",
  },
  products: [
    {
      id: "prod_1",
      name: "Classic Blue Baseball Cap",
      slug: "classic-blue-baseball-cap",
      description:
        "A timeless baseball cap in rich navy blue. Crafted from premium cotton twill with an adjustable strap for the perfect fit.",
      price: 86,
      compare_at_price: 99,
      category: "accessories",
      collections: ["caps", "accessories"],
      img: "https://i.imgur.com/wXuQ7bm.jpeg",
      images: [
        "https://i.imgur.com/wXuQ7bm.jpeg",
        "https://i.imgur.com/9DqEOV5.jpeg",
        "https://i.imgur.com/axsyGpD.jpeg",
      ],
      status: "active",
      stock_quantity: 45,
      sku_code: "CAP-BLU-001",
      created_at: "2025-01-15T10:00:00.000Z",
    },
    {
      id: "prod_2",
      name: "Classic Olive Chino Shorts",
      slug: "classic-olive-chino-shorts",
      description:
        "Relaxed-fit chino shorts in earthy olive green. Breathable cotton blend ideal for warm days and casual outings.",
      price: 84,
      compare_at_price: 110,
      category: "pants",
      collections: ["shorts", "pants"],
      img: "https://i.imgur.com/UsFIvYs.jpeg",
      images: ["https://i.imgur.com/UsFIvYs.jpeg"],
      status: "active",
      stock_quantity: 32,
      sku_code: "SHT-OLV-002",
      created_at: "2025-01-16T10:00:00.000Z",
    },
    {
      id: "prod_3",
      name: "Classic White Crew Neck T-Shirt",
      slug: "classic-white-crew-neck-t-shirt",
      description:
        "Essential crew neck tee in crisp white. Soft organic cotton with a relaxed fit — a wardrobe staple.",
      price: 39,
      category: "tops",
      collections: ["t-shirts", "tops"],
      img: "https://i.imgur.com/axsyGpD.jpeg",
      images: ["https://i.imgur.com/axsyGpD.jpeg"],
      status: "inactive",
      stock_quantity: 0,
      sku_code: "TEE-WHT-003",
      created_at: "2025-01-17T10:00:00.000Z",
    },
    {
      id: "prod_4",
      name: "Classic High-Waisted Athletic Shorts",
      slug: "classic-high-waisted-athletic-shorts",
      description:
        "Performance athletic shorts with a flattering high waist. Moisture-wicking fabric built for movement.",
      price: 43,
      compare_at_price: 55,
      category: "activewear",
      collections: ["shorts", "activewear"],
      img: "https://i.imgur.com/eGOUveI.jpeg",
      images: ["https://i.imgur.com/eGOUveI.jpeg"],
      status: "active",
      stock_quantity: 28,
      sku_code: "SHT-ATH-004",
      created_at: "2025-01-18T10:00:00.000Z",
    },
    {
      id: "prod_5",
      name: "Classic White Tee - Timeless Style and Comfort",
      slug: "classic-white-tee-timeless",
      description:
        "Premium white tee with a tailored silhouette. Double-stitched seams and heavyweight cotton for lasting quality.",
      price: 73,
      compare_at_price: 89,
      category: "tops",
      collections: ["t-shirts", "tops"],
      img: "https://i.imgur.com/Y54Bt8J.jpeg",
      images: [
        "https://i.imgur.com/Y54Bt8J.jpeg",
        "https://i.imgur.com/9DqEOV5.jpeg",
        "https://i.imgur.com/axsyGpD.jpeg",
      ],
      status: "active",
      stock_quantity: 60,
      sku_code: "TEE-WHT-005",
      created_at: "2025-01-19T10:00:00.000Z",
    },
    {
      id: "prod_6",
      name: "Classic Black T-Shirt",
      slug: "classic-black-t-shirt",
      description:
        "Versatile black tee that pairs with everything. Soft-touch fabric with a modern slim fit.",
      price: 35,
      category: "tops",
      collections: ["t-shirts", "tops"],
      img: "https://i.imgur.com/9DqEOV5.jpeg",
      images: ["https://i.imgur.com/9DqEOV5.jpeg"],
      status: "active",
      stock_quantity: 75,
      sku_code: "TEE-BLK-006",
      created_at: "2025-01-20T10:00:00.000Z",
    },
    {
      id: "prod_7",
      name: "Sleek White & Orange Wireless Gaming Controller",
      slug: "sleek-wireless-gaming-controller",
      description:
        "Ergonomic wireless controller with responsive triggers and long battery life. Compatible with PC and console.",
      price: 69,
      compare_at_price: 89,
      category: "electronics",
      collections: ["gaming", "accessories"],
      img: "https://i.imgur.com/ZANVnHE.jpeg",
      images: [
        "https://i.imgur.com/ZANVnHE.jpeg",
        "https://i.imgur.com/yVeIeDa.jpeg",
        "https://i.imgur.com/SolkFEB.jpeg",
      ],
      status: "active",
      stock_quantity: 18,
      sku_code: "GAM-CTL-007",
      created_at: "2025-01-21T10:00:00.000Z",
    },
    {
      id: "prod_8",
      name: "Sleek Wireless Headphone & Inked Earbud Set",
      slug: "sleek-wireless-headphone-earbud-set",
      description:
        "Complete audio bundle with over-ear headphones and matching earbuds. Active noise cancellation included.",
      price: 44,
      compare_at_price: 65,
      category: "electronics",
      collections: ["headphones", "accessories"],
      img: "https://i.imgur.com/yVeIeDa.jpeg",
      images: ["https://i.imgur.com/yVeIeDa.jpeg"],
      status: "active",
      stock_quantity: 22,
      sku_code: "AUD-HDP-008",
      created_at: "2025-01-22T10:00:00.000Z",
    },
    {
      id: "prod_9",
      name: "Sleek Comfort-Fit Over-Ear Headphones",
      slug: "sleek-comfort-fit-headphones",
      description:
        "Lightweight over-ear headphones with plush ear cushions. 30-hour battery and crystal-clear sound.",
      price: 28,
      category: "electronics",
      collections: ["headphones", "accessories"],
      img: "https://i.imgur.com/SolkFEB.jpeg",
      images: ["https://i.imgur.com/SolkFEB.jpeg"],
      status: "inactive",
      stock_quantity: 0,
      sku_code: "AUD-HDP-009",
      created_at: "2025-01-23T10:00:00.000Z",
    },
    {
      id: "prod_10",
      name: "Efficient 2-Slice Toaster",
      slug: "efficient-2-slice-toaster",
      description:
        "Compact stainless steel toaster with adjustable browning and wide slots. Perfect for busy mornings.",
      price: 48,
      compare_at_price: 62,
      category: "kitchen",
      collections: ["kitchen", "appliances"],
      img: "https://i.imgur.com/keVCVIa.jpeg",
      images: ["https://i.imgur.com/keVCVIa.jpeg"],
      status: "active",
      stock_quantity: 15,
      sku_code: "KIT-TST-010",
      created_at: "2025-01-24T10:00:00.000Z",
    },
  ],
  orders: [],
};
